### ISSUE TITLE
Fix zlib build on Alpine 3.21+ / GCC: implicit declaration of lseek in gzlib.c

### ISSUE THREAD

**Issue by rletocart** [ronpinkas/xharbour#109]
Hello,

When building xHarbour inside Alpine Linux 3.21.x (e.g. 3.21.5), the build fails in the bundled zlib under source/rtl/zlib/ with:

gzlib.c: error: implicit declaration of function 'lseek' [-Wimplicit-function-declaration]
The same tree still builds successfully on Alpine 3.20.3 (and typical Debian-based images). The regression appears with the newer toolchain shipped in Alpine 3.21 (stricter GCC defaults around implicit function declarations).

Cause

gzlib.c defines LSEEK as lseek (or lseek64 depending on macros) but relies on headers included via gzguts.h. On Linux/musl, lseek is declared in <unistd.h>, which is not included there. Older GCC treated this more leniently; newer GCC reports it as an error.

Proposed fix

Include <unistd.h> on POSIX platforms in source/rtl/zlib/gzguts.h, immediately after #include <fcntl.h>, guarded so Windows/Cygwin are unchanged, for example:

```
#include <fcntl.h>
#if !defined(_WIN32) && !defined(__CYGWIN__)
#  include <unistd.h>  /* lseek() for gzlib.c LSEEK */
#endif
```

This is a minimal, upstream-friendly change aligned with how zlib expects POSIX file APIs to be declared.

I can open a PR with this patch if that helps.

Bellow the diff

```diff
diff --git a/source/rtl/zlib/gzguts.h b/source/rtl/zlib/gzguts.h
index a3be3c99d..6904f86c7 100644
--- a/source/rtl/zlib/gzguts.h
+++ b/source/rtl/zlib/gzguts.h
@@ -30,6 +30,9 @@
 #  define _POSIX_SOURCE
 #endif
 #include <fcntl.h>
+#if !defined(_WIN32) && !defined(__CYGWIN__)
+#  include <unistd.h> /* lseek() for gzlib.c LSEEK (GCC strict sur Alpine) */
+#endif
 
 #ifdef _WIN32
 #  include <stddef.h>
```

Thanks very much for maintaining xHarbour.
