### ISSUE TITLE
Compile error MINGW+BISON

### ISSUE THREAD

**Issue by AndersonCardosoSilva-BR** [ronpinkas/xharbour#5]
[make_gc.log](https://github.com/ronpinkas/xharbour/files/11712445/make_gc.log)
C:\xhbgit>**make_gc all**
Creating System Files (ST) ...

Error:
> 'cat' nÆo ‚ reconhecido como um comando interno
> ou externo, um programa oper vel ou um arquivo em lotes.
> mingw32-make.exe: *** [obj/gc/hbver.c] Error 1

My batch env:
```
SET BISON_DIR=\GnuWin32\Bin
SET CC_DIR=\MinGW

SET PATH=C:\XHBGIT\BIN;C:\MinGW\bin;C:\GnuWin32\Bin;C:\WINDOWS
SET HB_DIR=C:\XHBGIT
SET HB_PATH=C:\XHBGIT
SET INCLUDE=C:\XHBGIT\INCLUDE;C:\MinGW\INCLUDE
SET LIB=C:\XHBGIT\LIB;C:\MinGW\LIB
```

**Comment by ronpinkas** [comment]
If I understand correctly it says "cat" is an unknown command - cat is a standard Linux command, you should check your MingW installation to see how make 'cat' work it's like dos's type command.

**Comment by marcosgambeta** [comment]
Add this:

SET HB_ARCHITECTURE=w32

**Comment by AndersonCardosoSilva-BR** [comment]
Hi Marcos,

I did it and it ran further but it still got errors:
`C:\xhbgit>make_gc all`
> In file included from source\rtl\hbsocket.c:232:0:
> source\rtl\hbsocket.c: In function 'hb_socketSetOsError':
> source\rtl\hbsocket.c:1123:12: error: 'ERROR_NOT_ENOUGH_MEMORY' undeclared (first use in this function)
>        case WSA_NOT_ENOUGH_MEMORY:
>             ^
> source\rtl\hbsocket.c:1123:12: note: each undeclared identifier is reported only once for each function it appears in
> source\rtl\hbsocket.c: In function 'hb_socketGetIFaces':
> source\rtl\hbsocket.c:4101:29: error: 'ERROR_BUFFER_OVERFLOW' undeclared (first use in this function)
>              if( dwResult == ERROR_BUFFER_OVERFLOW )
>                              ^~~~~~~~~~~~~~~~~~~~~
> source\rtl\hbsocket.c:4107:29: error: 'NO_ERROR' undeclared (first use in this function)
>              if( dwResult == NO_ERROR )
>                              ^~~~~~~~
> mingw32-make.exe: *** [obj\gc\hbsocket.o] Error 1
[make_gc.log](https://github.com/ronpinkas/xharbour/files/11793827/make_gc.log)
[make0_gc.log](https://github.com/ronpinkas/xharbour/files/11793828/make0_gc.log)

Logs are attached.

My env batch file:
```
SET BISON_DIR=\GnuWin32\Bin
SET CC_DIR=\MinGW
SET HB_ARCHITECTURE=w32

SET PATH=C:\XHBGIT\BIN;C:\MinGW\bin;C:\GnuWin32\Bin;C:\WINDOWS
SET HB_DIR=C:\XHBGIT
SET HB_PATH=C:\XHBGIT
SET INCLUDE=C:\XHBGIT\INCLUDE;C:\MinGW\INCLUDE
SET LIB=C:\XHBGIT\LIB;C:\MinGW\LIB
```

**Comment by marcosgambeta** [comment]
Anderson,

Try the  steps below:

1) Use a recent version of the C/C++ compiler:

Suggestion:
https://github.com/brechtsanders/winlibs_mingw/releases/download/13.1.0-16.0.5-11.0.0-msvcrt-r5/winlibs-i686-posix-dwarf-gcc-13.1.0-mingw-w64msvcrt-11.0.0-r5.7z
(from https://winlibs.com)

2) Compile using only the settings below (adjust the paths):

SET CC_DIR=C:/mingw32/
SET BISON_DIR=C:/gnuwin32/bin
SET HB_ARCHITECTURE=w32
CALL make_gc.bat all

Works for me. I get only warning's and none errors.

**Comment by AndersonCardosoSilva-BR** [comment]
Hooray!! It worked with GCC v13.1.0!!! No warnings and no errors!!! 
Thanks, Marcos!

It was missing one more var:
`SET HB_COMPILER=mingw32`
After that it compiled and copied everything to the right place.
That GCC v13.1.0 creates mingw32 folder and not mingw.
My full environment was this:
```
SET BISON_DIR=\GnuWin32\Bin
SET CC_DIR=\MinGW32
SET HB_ARCHITECTURE=w32
SET HB_COMPILER=mingw32
```
All working 100%
